### ISSUE TITLE
Initial route param doesn't work for Tabs component

### ISSUE THREAD

**Issue by kishieel** [expo/router#763]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

After starting application with Tabs I got "Unmatched route" screen despite the initial routes I had set.

### Minimal reproducible example

Fresh expo installation with expo-router.

```
// app/_layout.tsx

export const unstable_settings = {
    initialRouteName: '(lobby)',
};

function RootLayoutNav() {
    return (
        <>
            <Stack initialRouteName="(lobby)">
                <Stack.Screen name="(lobby)" options={{ headerShown: false }} />
            </Stack>
        </>
    );
}
```

```
// app/(lobby)/_layout.tsx

export default function TabLayout() {
    return (
        <Tabs initialRouteName={AScreen.name}>
            <Tabs.Screen name={AScreen.name} />
            <Tabs.Screen name={BScreen.name} />
        </Tabs>
    );
}
```

When application start I got "Unmatched route". After logging result of useNavigation and usePathname hook I get '/(lobby) /--' which seems not to be my preferred initial route.

**Comment by feRpicoral** [comment]
I'm super new to expo router myself, but from my understanding you have to have an `index` route. You only have layout routes.

**Comment by EvanBacon** [comment]
`initialRouteName` came from React Navigation, we'll probably rename it. `initialRouteName` renders the default screen for a navigator, this is useful for modals where you always want a screen under the modal. We don't have a dedicated static redirect-config API, I recommend creating an index route and redirecting to the desired screen inside. Preferably you'd just have an index route.

**Comment by BoraALAP** [comment]
@EvanBacon I have tabs and under tabs I have home page like app/(user)/home/index and I would like that index to be the landing screen for the whole app. However, because I don't have app/index, as soon as I launch the app it comes empty. I have initialized Stack initialRouteName="home" in RootLayout. still not responding the way i believe it should be. 

Is there a way to indicate the landing screen in the root layout without redirecting? 

I have checked the tabs example it is doing what I'm looking for and I set the same structure but no luck.

**Comment by skfaisal93** [comment]
Any solution?

**Comment by ivanmartinvalle** [comment]
My workaround: always add an `index.ts`, and then hide it.

```typescript
const Index = () => {
  return null
}

export default Index
```

```tsx
<Tabs.Screen redirect name="index" />
```

**Comment by nitinpatelm** [comment]
> My workaround: always add an `index.ts`, and then hide it.
> 
> ```ts
> const Index = () => {
>   return null
> }
> 
> export default Index
> ```
> 
> ```tsx
> <Tabs.Screen redirect name="index" />
> ```

Thanks. Working for me.

**Comment by mxmtsk** [comment]
> My workaround: always add an `index.ts`, and then hide it.
> 
> ```ts
> const Index = () => {
>   return null
> }
> 
> export default Index
> ```
> 
> ```tsx
> <Tabs.Screen redirect name="index" />
> ```

This works good in general, but my issue is that I want the middle Tab (out of my three) to be the default one. I have no idea how to achieve this. Currently I'm redirecting inside my index route to the middle route, but you can see the empty index component for a short time, which is not nice

**Comment by stevenwaller** [comment]
@mxmtsk Instead of setting the `redirect` prop on the `Tabs.Screen` you can use the `Redirect` component inside your `index.tsx` to redirect to a specific tab.

```tsx
// index.tsx
import { Redirect } from "expo-router";

const Index = () => {
	return <Redirect href="/middleTab" />;
};
export default Index;
``` 

Found that here: https://github.com/expo/router/issues/428#issuecomment-1515743869

**Comment by ThisIsArnav** [comment]
> @mxmtsk Instead of setting the `redirect` prop on the `Tabs.Screen` you can use the `Redirect` component inside your `index.tsx` to redirect to a specific tab.
> 
> ```tsx
> // index.tsx
> import { Redirect } from "expo-router";
> 
> const Index = () => {
> 	return <Redirect href="/middleTab" />;
> };
> export default Index;
> ```
> 
> Found that here: [#428 (comment)](https://github.com/expo/router/issues/428#issuecomment-1515743869)

But when we add the above index.tsx file in app directory, there is a empty tab bar icon which gets rendered in the tab bar navigation.
<img width="959" alt="image" src="https://github.com/user-attachments/assets/12341e17-9084-46c8-a838-3b59351000a4">

**Comment by ThisIsArnav** [comment]
> > @mxmtsk Instead of setting the `redirect` prop on the `Tabs.Screen` you can use the `Redirect` component inside your `index.tsx` to redirect to a specific tab.
> > ```tsx
> > // index.tsx
> > import { Redirect } from "expo-router";
> > 
> > const Index = () => {
> > 	return <Redirect href="/middleTab" />;
> > };
> > export default Index;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Found that here: [#428 (comment)](https://github.com/expo/router/issues/428#issuecomment-1515743869)
> 
> But when we add the above index.tsx file in app directory, there is a empty tab bar icon which gets rendered in the tab bar navigation. <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/76993824/366581521-12341e17-9084-46c8-a838-3b59351000a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzk1NTksIm5iZiI6MTcyNjA3OTI1OSwicGF0aCI6Ii83Njk5MzgyNC8zNjY1ODE1MjEtMTIzNDFlMTctOTA4NC00NmM4LWE4MzgtM2I1OTM1MTAwMGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE4MjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNWMzNjljYjkzOTc4MWM0OWU5N2IzMTkwYmM4Y2U3NWUyYTIxYWIwY2M3MzdlZTdjYTcxODczYWM2YzQ3YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RQM398MCJ4CJG_S4kAd2S4cHC2ioGj8yB8NGPQpTr9E">

I have implemented this to hide that extra index button:

`// app/(tabs)/_layout.js
import { Tabs } from 'expo-router';

export default function TabsLayout() {
  return (
    <Tabs>
      <Tabs.Screen
        name="index"
        options={{
          // This hides the tab button for the "index" route
          tabBarButton: () => null,
        }}
      />
      <Tabs.Screen name="home" options={{ title: 'Home', icon: 'home-icon' }} />
      <Tabs.Screen name="profile" options={{ title: 'Profile', icon: 'profile-icon' }} />
    </Tabs>
  );
}
`

**Comment by atharvasune** [comment]
Still facing the issue.. and while the work arounds work.. is there a way to se the default route ?

**Comment by gsarpy** [comment]
> > > @mxmtsk Instead of setting the `redirect` prop on the `Tabs.Screen` you can use the `Redirect` component inside your `index.tsx` to redirect to a specific tab.
> > > ```tsx
> > > // index.tsx
> > > import { Redirect } from "expo-router";
> > > 
> > > const Index = () => {
> > > 	return <Redirect href="/middleTab" />;
> > > };
> > > export default Index;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Found that here: [#428 (comment)](https://github.com/expo/router/issues/428#issuecomment-1515743869)
> > 
> > 
> > But when we add the above index.tsx file in app directory, there is a empty tab bar icon which gets rendered in the tab bar navigation. <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/76993824/366581521-12341e17-9084-46c8-a838-3b59351000a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzk1NTksIm5iZiI6MTcyNjA3OTI1OSwicGF0aCI6Ii83Njk5MzgyNC8zNjY1ODE1MjEtMTIzNDFlMTctOTA4NC00NmM4LWE4MzgtM2I1OTM1MTAwMGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE4MjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNWMzNjljYjkzOTc4MWM0OWU5N2IzMTkwYmM4Y2U3NWUyYTIxYWIwY2M3MzdlZTdjYTcxODczYWM2YzQ3YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RQM398MCJ4CJG_S4kAd2S4cHC2ioGj8yB8NGPQpTr9E">
> 
> I have implemented this to hide that extra index button:
> 
> `// app/(tabs)/_layout.js import { Tabs } from 'expo-router';
> 
> export default function TabsLayout() { return ( <Tabs.Screen name="index" options={{ // This hides the tab button for the "index" route tabBarButton: () => null, }} /> <Tabs.Screen name="home" options={{ title: 'Home', icon: 'home-icon' }} /> <Tabs.Screen name="profile" options={{ title: 'Profile', icon: 'profile-icon' }} /> ); } `

According to the docs the way to hide an item from the tab bar is to set the `<Tabs.Screen>` `href` to `null` inside the `options={{}}` 

https://docs.expo.dev/router/advanced/tabs/#hiding-a-tab

I really wish there was a simple flag like `hideUnlisted: true` for the `<Tabs>` component screen options instead of having to manually address each individual screen you don't want in your tab bar by using a redundant `<Tabs.Screen` for every single screen you want to omit. Makes the code much messier by requiring a bunch of logic that really doesn't need to be there.

**Comment by Arsenii-Zhelobetskyi** [comment]
@ThisIsArnav, the redirect thing actually cause a crash, something like "unable to find viewState". When you try to hit back button several times on the initial page. I'm using dev build though

**Comment by MahmoudBahar** [comment]
is there any updates regarding that issue?
